# Usa la imagen base de Python 3.9
FROM python:3.9

# Establece la variable de entorno para evitar problemas de codificación
ENV PYTHONUNBUFFERED=1

# Crea el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos a /app
COPY requirements.txt .

# Instala los requerimientos
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación a /app
COPY . .

# Establece el comando por defecto para correr la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
